---
title: "data analysis"
author: "Dom Owens"
date: "27/04/2020"
output: html_document
---

```{r}
library(tidyverse)
bf_ <- ts(bf)
bf_ <- na.fill(bf_, fill = "extend")
bf_ <-bf_[,c(-2,-13)]

library(ggfortify)
#bf_ts_0 <- as.matrix(t( t(bf_) - (model$x.mean))) #centre
autoplot(bf_, facets=T, main = "Risk Measures, 1980-1985")
```

```{r}


autoplot(ts(bf_sub_0), facets=F, main = "Risk Measures, 1980-1985")
model_ <- ar(bf_sub_0, demean = T, order.max = 4, method = "ols")  
A_ <- cbind(model_$x.intercept,  matrix(model_$ar[1,,], nrow=6, ncol=6), matrix(model_$ar[2,,], nrow=6, ncol=6),  matrix(model_$ar[3,,], nrow=6, ncol=6),  
           matrix(model_$ar[4,,], nrow=6, ncol=6) )
eps_ <- model_$resid
bf_test <- test_Score(x=as.matrix(bf_sub_0), p=4, G=200, Phi = A_, eps = as.matrix(eps_), alpha = 0.05, estim = "DiagH")
bf_test

#bf_wald_ <- test_Wald(x=as.matrix(bf_sub_0), p=1, G=250, estim = "DiagC")
#bf_wald_
```

```{r}
library(igraph)
c <- cov(bf, use = "pairwise.complete.obs" )
g <-graph_from_adjacency_matrix(c, mode = "undirected", weighted = T)
plot(g, vertex.color=10)
```

```{r}
colSums(is.na(bf_))
bf_ <- na.fill(bf_, fill = "extend")
bf_sub <- bf_[,1:3]#c(6:10)]
autoplot(bf_sub, facets = F, main="Risk Measure Panel")
library(urca)
ur.df(bf_sub[,1], type="trend", selectlags = "AIC")
ur.df(bf_sub[,2], type="trend", selectlags = "AIC")
ur.df(bf_sub[,3], type="trend", selectlags = "AIC")
d_bf <- ts(diff(bf_sub))
autoplot(d_bf, main = "Risk Measure Panel, First Difference")
#bf_sub_0 <- as.matrix(t( t(bf_sub) - colMeans(bf_sub) )) #centrebf_sub - colMeans(bf_sub)
```
```{r}
model_d <- ar(d_bf, demean = T, order.max = 3, method = "ols")  
A_d <- cbind(model_d$x.intercept,  matrix(model_d$ar[1,,], nrow=3, ncol=3), matrix(model_d$ar[2,,], nrow=3, ncol=3)) #,matrix(model_d$ar[3,,], nrow=3, ncol=3))
eps_d <- model_d$resid
t_d <- test_Score(d_bf, p=2, G=200, Phi=A_d, eps = eps_d, estim = "DiagH")
t_d_w <- test_Wald(d_bf, p=2, G=200, alpha=0.05, estim = "DiagH") 
```

```{r}
A1_r1 <- matrix( c(.5, .1, .1, 
                 .1, .5,  .1, 
                 .1, .1, .5), nrow = 3, ncol = 3 ) 
A2_r1 <- matrix( c(-.2, .2, .2, 
                   .2, -.2,  .2, 
                   .2, .2, -.2), nrow = 3, ncol = 3 ) 
  e1 <- matrix(rnorm(3 * 500, 0, .5),ncol=3)
  e2 <- matrix(rnorm(3 * 500, 0, .5),ncol=3)
  e3 <- matrix(rnorm(3 * 500, 0, .5),ncol=3)
  e4 <- matrix(rnorm(3 * 500, 0, .5),ncol=3)
  graphdata <- rbind(rSim_p2(A1_r1,A2_r1,e1),rSim_p2(A1_r1,A2_r1,e2),rSim_p2(A1_r1,A2_r1,e3),rSim_p2(A1_r1,A2_r1,e4)) 
  model_graph <- ar(graphdata, demean = T, order.max = 2, method = "ols")  
  A_graph <- cbind(model_graph$x.intercept,  matrix(model_graph$ar[1,,], nrow=3, ncol=3), matrix(model_graph$ar[2,,], nrow=3, ncol=3)) #,matrix(model_d$ar[3,,], nrow=3, ncol=3))
  eps_graph <- model_graph$resid
  t_graph <- test_Score(graphdata, p=2, G=200, Phi=A_graph, eps = eps_graph, estim = "DiagH")
  S <- diag(diag(cov(model_graph$resid, use="pairwise.complete.obs")))
  AG <- rbind( cbind(S,A1_r1,A2_r1),cbind(0,0,0,S,A1_r1),cbind(0,0,0, 0,0,0, S) )
  rownames(AG) <- colnames(AG) <- c("Y_t(1)","Y_t(2)","Y_t(3)","Y_t-1(1)","Y_t-1(2)","Y_t-1(3)","Y_t-2(1)","Y_t-2(2)","Y_t-2(3)")
  library(igraph)
  ag <-graph_from_adjacency_matrix(t(AG), mode = "directed", weighted = T)
  plot(ag)
```

```{r}
#install.packages("remotes")
#remotes::install_github("Dom-Owens-UoB/ngc")
#detach("package:NGC",unload = T)
library(NGC) #rdrr.io/github/njetzel/ngc
        #graphtensor <- array(t(graphdata), c(1,dim(graphdata)) )
covNames <- c("Y1","Y2","Y3")
Tlasso_model <- ngc(X = t(graphdata), d=3, typeIerr = 1, typeIIerr = 0.01,  maxIter=1000, estMethod = "truncate", covNames=covNames)
Tlasso_model$estMat
plot(Tlasso_model$dag, color = "SkyBlue2")
```

```{r}
Tlasso_full <- ngc(X = t(d_bf), d=4, typeIerr = 0.3, typeIIerr = 0.05, maxIter=5000, estMethod = "truncate", eps = 1e-5, covNames=covNames)
Tlasso_full$estMat
tkplot(Tlasso_full$dag, vertex.color=c(rep(10,3), rep(11,3), rep(12,3), rep(13,3), rep(14,3)  ))
```

```{r}
Tlasso_change <- ngc(X = t(d_bf[1829:(dim(d_bf)[1]), ]), d=4, typeIerr = 0.9, typeIIerr = 0.05, maxIter=10000, estMethod = "truncate", eps = 1e-5, covNames=covNames)
Tlasso_change$estMat
tkplot(Tlasso_change$dag, vertex.color=c(rep(10,3), rep(11,3), rep(12,3), rep(13,3), rep(14,3)  ))
```
```{r}
Tlasso_prechange <- ngc(X = t(d_bf[1:1829, ]), d=4, typeIerr = 0.9, typeIIerr = 0.05, maxIter=10000, estMethod = "truncate", eps = 1e-5, covNames=covNames)
Tlasso_prechange$estMat
tkplot(Tlasso_prechange$dag, vertex.color=c(rep(10,3), rep(11,3), rep(12,3), rep(13,3), rep(14,3)  ))

```





```{r}
library(Rcpp)
library(RcppParallel)
library(RcppArmadillo)
library(Matrix)
sourceCpp(file = "Wald_RcppParallel.cpp")
```
```{r}
library(tidyverse); library(openxlsx); library(zoo)
bf <- read.xlsx("bf_for_dom.xlsx", detectDates = T)
bf_ <- ts(bf)
bf_ <- bf_[,-1]
bf_ <- na.fill(bf_, fill = "extend")
#bf_ <-bf_[,c(-2,-13)]
#time(bf_) <- bf$Index
library(ggfortify)
#bf_ts_0 <- as.matrix(t( t(bf_) - (model$x.mean))) #centre
#autoplot(bf_[,1], facets=F, main = "Risk Measures")
dates <- bf$Index[c(1,1001,2001,3001,4001)]
autoplot(bf_,facets = F, main="Risk Measures, 2000-12-22 - 2018-04-24") + scale_x_continuous(breaks = c(1,1001,2001,3001,4001), labels= dates )
```


```{r}
colSums(is.na(bf))
#bf_ <- na.fill(bf_, fill = "extend")
bf_sub <- bf_[,c(1,22:24)]#c(6:10)]
autoplot(bf_sub, facets = F, main="Risk Measure Panel")
library(urca)
ur.df(bf_sub[,1], type="trend", selectlags = "AIC")
ur.df(bf_sub[,2], type="trend", selectlags = "AIC")
ur.df(bf_sub[,3], type="trend", selectlags = "AIC")
d_bf <- ts(diff(bf_sub))
autoplot(d_bf, main = "Risk Measure Panel, First Difference")+ scale_x_continuous(breaks = c(1,1001,2001,3001,4001), labels= dates )
```
```{r}
model_d <- ar(d_bf, demean = T, order.max = 2, method = "ols")  
A_d <- cbind(model_d$x.intercept,  matrix(model_d$ar[1,,], nrow=4, ncol=4), matrix(model_d$ar[2,,], nrow=4, ncol=4)) #,matrix(model_d$ar[3,,], nrow=3, ncol=3))
eps_d <- model_d$resid
t_d <- test_Score(d_bf, p=2, G=400,alpha=0.01, Phi=A_d, eps = eps_d, estim = "DiagH")
t_d_w <- test_Wald_new(d_bf, p=2, G=400, alpha=0.01, estim = "DiagH") 
```

```{r}
xmu <- c(rep(0,400),rep(1,200), rep(0.5,400))
xsingle <- rnorm(1000) + xmu
plot.ts(xsingle, ylab="X_t");lines(xmu,col="green")
```
```{r}
library(mosum)
ms <-mosum(xsingle, G=1000^.66)
plot(ms, "mosum")
```

```{r}
aa <- matrix(data=c(0.7,0.1,0.1, 0.1,0.7,0.1, 0.1,0.1,0.7), 3,3 )
aa_2 <- matrix(data=c(-0.5,0.3,0.3, 0.3,-0.5,0.3, 0.3,0.3,-0.5), 3,3 )
aa_3 <- aa^2
edp2_1 <- matrix(rnorm(1000*3, 0, 0.1), ncol = 3) ;edp2_2 <- matrix(rnorm(1000*3, 0, 0.1), ncol = 3);edp2_3 <- matrix(rnorm(1000*3, 0, 0.1), ncol = 3)
dp2_Data1 <- rSim(aa, edp2_1)
dp2_Data2 <- rSim(aa_2, edp2_2)
dp2_Data3 <- rSim(aa_3, edp2_3)

dp2_change <- ts(rbind(dp2_Data1, dp2_Data2,dp2_Data3) )
dp2_model <- ar(dp2_change, order.max = 1, demean = T, method = "ols")
dp2_a <- cbind(dp2_model$x.intercept,  dp2_model$ar)
dp2_eps <- dp2_model$resid
plot(dp2_change, main="Change in Autoregression"); abline(v = c(1000,2000), col= "red")
```

